# This is a GitHub Actions workflow file
# It defines what happens when code is pushed to GitHub

name: CI Pipeline # This name appears in GitHub Actions tab

# WHEN should this workflow run?
on:
  push:
    branches: [master, develop] # Run on pushes to master or develop branch
  pull_request:
    branches: [master] # Run on pull requests to master branch

# WHAT should this workflow do?
jobs:
  # Job 1: Run tests and builds
  test-and-build:
    runs-on: ubuntu-latest # Use Ubuntu Linux virtual machine
    
    steps:
      # Step 1: Get the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Get full history so Nx can detect what changed
          fetch-depth: 0
      
      # Step 2: Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js version 20
          
      # Step 3: Install pnpm (our package manager)
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      # Step 4: Verify lockfile is committed
      - name: Check lockfile
        run: |
          echo "Checking if pnpm-lock.yaml is committed..."
          if [ -f pnpm-lock.yaml ]; then
            echo "✅ pnpm-lock.yaml exists"
            ls -la pnpm-lock.yaml
          else
            echo "❌ pnpm-lock.yaml missing - this will cause CI issues"
            exit 1
          fi
          
      # Step 5: Install all dependencies
      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "Lockfile found - using frozen install"
            pnpm install --frozen-lockfile
          else
            echo "No lockfile found - installing normally"
            pnpm install
          fi
        
      # Step 5: Lint only what changed
      - name: Lint affected projects
        run: pnpm run affected:lint
        
      # Step 6: Test only what changed
      - name: Test affected projects  
        run: pnpm run affected:test --parallel=3
        # --parallel=3 runs up to 3 tests at the same time
        
      # Step 7: Build only what changed
      - name: Build affected projects
        run: pnpm run affected:build --parallel=3
